spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 287604875831-rgetb5huq40lrs2i980d70nu2ic27e3b.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/contacts.readonly

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMs: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:4200/oauth2/redirect